import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Banner from '../src/modules/Banner';
import ScrollSequence from '../src/modules/ImageSequence';
import { exterior1, interior } from 'public/assets/seq/seq';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { EngineSection } from '@src/components/EngineSection';
import { SwiperSection } from '../src/components/SwiperSection';
import ParallaxSection from '@src/components/parallex';
import ParallaxSectionSecond from '@src/components/parallex2';
import { EngineTypesSection } from '@src/components/EngineTypes';
import AmbiantLight from '@src/components/ambiant';
import VRShowroom from '@src/modules/VRShowroom';
import Dimensions from '@src/components/dimensions';
import KiaConnect from '@src/components/kiaConnect';
import Specs from '@src/components/specs';
import { FloatingTextThree } from '@src/components/floatingText3';
import { Exterior } from '@src/components/exterior';
import { Interior } from '@src/components/interior';

export default function Home() {
  const { t, i18n } = useTranslation('common');
  const isArabic = i18n?.language == 'ar'; // Replace with your actual language detection logic
  const [mounted, setMounted] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false)

  
  const router = useRouter();
  const { locale, query } = useRouter();
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // or a loading state
  }



  return (
    <main className="relative">

      <Head>
        {router.locale == 'ar' ? <title>كيا تاسمان - البروشور الرقمي</title> : <title>Kia Tasman - Digital Brochure</title>}
        <link rel="icon" href="/kia.ico"  />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Banner />
     
      <div className='w-screen h-screen'>
        <EngineSection />
      </div>
      <div className='w-screen h-[70vh]' id='exterior'>
        <Exterior />
     </div>
           <div className="relative"  style={{ zIndex: 1000 }}>
        <ScrollSequence
          id="canvas4"
          imagesUrl={exterior1}
          totalFrames={exterior1?.length}
         
        />
      </div>
      <SwiperSection height={'min-h-[40vh]'} id={0} />
      <VRShowroom />
      <VRShowroom showControl={true} />
      <Interior/>
      <div className="relative"  style={{ zIndex: 1000 }}>
        <ScrollSequence
          id="canvas4"
          imagesUrl={interior}
          totalFrames={interior?.length}
         
        />
      </div>
      <FloatingTextThree/>
      <AmbiantLight isModalOpen={isModalOpen} setIsModalOpen={setIsModalOpen} />
      <SwiperSection height={'min-h-[40vh]'} id={1} />
      <ParallaxSection />
      <EngineTypesSection />

      <ParallaxSectionSecond />
      <div className=' bg-white '>
        <SwiperSection height={'min-h-[65vh]'} id={3} noBg dark={true} />
      </div>
      <div className='h-[100vh]'>
        <KiaConnect />
     </div>
      <Dimensions />
      <Specs/>
      {isModalOpen ?
        <div className='fixed w-screen h-screen bg-black/90 z-[10000] flex flex-col items-center justify-center  left-0 top-0'>
          <div className="bg-white rounded-xl flex flex-col  items-end w-[650px]  relative" >
            <button onClick={() => {
              document.body.style.overflow = 'auto'
              setIsModalOpen(false)
            }} className="text-black text-3xl cursor-pointer rounded-full w-10 h-10 bg-white absolute end-4 top-4 ">×</button>
            <div className='flex flex-col items-center  w-full'>
              <img src={isModalOpen == 1 ? 'https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/9103fa63-4b86-45ef-e14a-c0bba7424000/public' : isModalOpen == 2 ? 'https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/310ca7e9-3708-4516-35a0-d81e50342100/public' : isModalOpen == 3 ? 'https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/7ce5f2db-cd28-475f-2909-5ed588c6a100/public' : 'https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/ebfb9ad5-4957-46f6-6c96-b3cc3bdd0c00/public'} width={'100%'} height={'70%'} alt="Analytics Overview" className="rounded-t-xl" />
              <div className="p-6 flex flex-col gap-3 ">
                <div className={`text-[#333] text-center ${isArabic ? 'font-[GSSMedium]' : 'font-[InterBold]'} text-[20px]`}>{isModalOpen == 1 ? isArabic ? `شاشة بانورامية مدمجة` : 'Panoramic Integrated Display' : isModalOpen == 2 ? isArabic ? `شاحن هاتف لاسلكي مزدوج` : 'Dual Wireless Charger' : isModalOpen == 3 ? isArabic ? `طاولة مركزية` : 'Console Table' : isArabic ? `مفتاح تحكم بمقعد الراكب` : 'Passenger Walk-in Switch'}</div>
                <div className={`text-[#666]  text-center ${i18n?.language == 'ar' ? 'Font-[GSSMedium]' : 'font-[InterRegular]'} text-sm`}
                  style={{
                    fontFamily: i18n?.language == 'ar' ? 'Font-[GSSMedium]' : 'font-[InterRegular]'
                }}
                >
                  {isModalOpen == 1 ?
                    (isArabic ?
                      `استمتع بنظام المعلومات والترفيه الأحدث مع أكبر شاشة في فئتها. كما يمكنك تحديث سيارتك بسهولة عن طريق التحديثات الهوائية (OTA).`
                      : `Enjoy the brand's state-of-the-art infotainment system with the widest display in its class. You can also maintain your vehicle to the latest through OTA Update.`)
                    : isModalOpen == 2 ?
                      (isArabic ?
                        `ابقَ في حالة تواصل وشحن دائم للأجهزة عن طريق شاحنين لاسلكيين وتوصيلات USB Type-C متعددة.`
                        : `Keep your phone & devices charged on the go with available wireless charging trays & multiple USB Type-C chargers.`)
                      : isModalOpen == 3 ?
                        (isArabic ?
                          `تحوّل الطاولة القابلة للتمدد في الكونسول سيارتك إلى مكتبٍ متنقل، حيث يمكنك فتح جزء من مسند الذراع لتكوين طاولة عريضة مناسبة للحاسوب أو المستندات ، أو حتى لتناول وجبة خفيفة.`
                          : `An expandable console table turns the Kia Tasman into a private mobile office. Unfold the upper part of the console armrest to create a wide table you can use for checking your laptop or documents—or enjoying a simple meal.`)
                        : (isArabic ?
                          `يمكنك تعديل وضع مقعد الراكب الأمامي للأمام أو الخلف أو تعديل الزاوية بكل سهولة من كرسي السائق أو المقاعد الخلفية، مما يعزز سهولة الدخول والخروج وراحة ركاب المقاعد الخلفية.`
                          : `This function allows you to adjust the forward/backward position and angle of the passenger seat from the driver's seat or the rear seat to improve the convenience of getting in and out of the vehicle and living in the rear seat.`)
                  }
                </div>
                {isModalOpen == 1 ?
                  <p
                    
                    style={{
                      fontFamily: i18n?.language == 'ar' ? 'Font-[GSSMedium]' : 'font-[InterRegular]'
                    }}
                    className={`text-[#1a1a1a] text-center ${i18n?.language == 'ar' ? 'Font-[GSSMedium]' : 'font-[InterRegular]'} text-xs`}>({isArabic ? 'بعض المزايا قد يختلف توفرها حسب البلد' : 'Some features may vary based on the market'})</p>
               : null}
              </div>
            </div>
          </div>
        </div> : null}
    </main>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}
