import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import VRShowroom from '../src/modules/VRShowroom';
import Banner from '../src/modules/Banner';
import ScrollSequence from '../src/modules/ImageSequence';
import { exterior, exterior1, ScreenImages } from 'public/assets/seq/seq';
import { useEffect, useState } from 'react';
import { SpecsCards } from '@src/modules/specsCards';
import { SpecsSection } from '@src/modules/Specs';
import { useRouter } from 'next/router';
import FeaturesCards1 from '@src/modules/CardSwipper/Cards1';
import FeaturesCards2 from '@src/modules/CardSwipper/Cards2';
import FeaturesCards3 from '@src/modules/CardSwipper/Cards3';
import ParallaxSectionTV from '../src/components/ParallexTv';
import { EngineSection } from '@src/components/EngineSection';
export default function Home () {
    const { t } = useTranslation('common');
    const [selectedFeature, setSelectedFeature] = useState(0);
    const isArabic = false; // Replace with your actual language detection logic
    const [mounted, setMounted] = useState(false);
    const router = useRouter();
    const { locale, query } = useRouter();
    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) {
        return null; // or a loading state
    }

    return (
        <main className="relative">
            <Head>
                {router.locale == 'ar' ? <title>كيا K4 - البروشور الرقمي</title> : <title>Kia K4 - Digital Brochure</title>}
                <link rel="icon" href="/kia.ico" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Banner />
            <div className='w-[full]  flex  md:hidden bg-[#05141F]  py-[50px]  items-start space-between'>
                <div className={`w-full flex gap-10 flex-row  flex-wrap md:flex-nowrap justify-center md:justify-start md:items-start `}>
                    <div className='flex flex-col items-center w-[145px]'>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="#ffffff"
                            height="54px"
                            width="54px"
                            id="Layer_1"
                            viewBox="0 0 512 512"
                            xmlSpace="preserve"
                        >
                            <g transform="translate(1 1)">
                                <g>
                                    <path d="M502.467,186.733h-34.133c-3.413,0-6.827,2.56-7.68,5.973l-23.893,70.827h-23.04l-23.04-38.4   c-1.707-2.56-4.267-4.267-7.68-4.267h-34.133v-25.6c0-5.12-3.413-8.533-8.533-8.533H280.6V152.6h25.6   c5.12,0,8.533-3.413,8.533-8.533v-51.2c0-5.12-3.413-8.533-8.533-8.533H152.6c-5.12,0-8.533,3.413-8.533,8.533v51.2   c0,5.12,3.413,8.533,8.533,8.533h25.6v34.133h-68.267c-2.56,0-4.267,0.853-5.973,2.56s-2.56,3.413-2.56,5.973v25.6H41.667   c-5.12,0-8.533,3.413-8.533,8.533v51.2H16.067V255c0-5.12-3.413-8.533-8.533-8.533S-1,249.88-1,255v68.267   c0,5.12,3.413,8.533,8.533,8.533s8.533-3.413,8.533-8.533v-25.6h17.067v68.267c0,5.12,3.413,8.533,8.533,8.533h64l31.573,47.787   c1.707,1.707,4.267,3.413,6.827,3.413H383c3.413,0,5.973-1.707,7.68-5.12l23.04-46.08h23.893l23.04,46.08   c1.707,3.413,4.267,5.12,7.68,5.12h34.133c5.12,0,8.533-3.413,8.533-8.533V195.267C511,190.147,507.587,186.733,502.467,186.733z    M161.133,101.4h136.533v34.133h-25.6h-85.333h-25.6V101.4z M195.267,152.6h68.267v34.133h-68.267V152.6z M50.2,357.4V237.933   h51.2V357.4H50.2z M377.027,408.6H148.333l-29.867-45.204V229.4v-25.6h68.267h85.333H331.8v25.6c0,5.12,3.413,8.533,8.533,8.533   h37.547l22.187,36.978v87.609L377.027,408.6z M417.133,357.4v-76.8H434.2v76.8H417.133z M493.933,408.6h-20.48l-22.187-42.789   v-93.714l23.04-68.297h19.627V408.6z"></path>
                                </g>
                            </g>
                        </svg>
                        <p className={`text-[17px] ${locale == 'ar' ? "font-['GSSMedium']" : "font-[InterBold]"} text-white mt-2.5`}>{t('engineTurbo')?.split('1.6')[0]}<span className='font-["InterBold"]'>1.6</span>{t('engineTurbo')?.split('1.6')[1]} </p>
                        <p className={`text-[14px] leading-[16px] ${locale == 'ar' ? "font-['GSSLight']" : "font-[InterRegular]"} text-white`}> {t('engineHorsepower')?.split('190')[0]}
                            <span className='font-[InterRegular]'>190</span>
                            {t('engineHorsepower')?.split('190')[1]}
                        </p>
                    </div>
                    <div className='flex flex-col items-center w-[145px]'>
                        <svg xmlns="http://www.w3.org/2000/svg"
                            height="54px"
                            fill='#ffffff'
                            width="54px"
                            viewBox="0 0 74 74"
                            id="gearbox">
                            <path d="M37,72A35,35,0,1,1,72,37,35,35,0,0,1,37,72ZM37,4A33,33,0,1,0,70,37,33,33,0,0,0,37,4Z"></path><path d="M55,58a4,4,0,0,1-4-4V41H41V54a4,4,0,0,1-8,0V41H23V54a4,4,0,0,1-8,0V20a4,4,0,0,1,8,0V33H33V20a4,4,0,0,1,8,0V33H51V20a4,4,0,0,1,8,0V54A4,4,0,0,1,55,58ZM40,39H52a1,1,0,0,1,1,1V54a2,2,0,0,0,4,0V20a2,2,0,0,0-4,0V34a1,1,0,0,1-1,1H40a1,1,0,0,1-1-1V20a2,2,0,0,0-4,0V34a1,1,0,0,1-1,1H22a1,1,0,0,1-1-1V20a2,2,0,0,0-4,0V54a2,2,0,0,0,4,0V40a1,1,0,0,1,1-1H34a1,1,0,0,1,1,1V54a2,2,0,0,0,4,0V40A1,1,0,0,1,40,39Z"></path></svg>
                        <p className={`text-[17px] ${locale == 'ar' ? "font-['GSSMedium']" : "font-[InterBold]"} text-white mt-2.5`}>{t('Transmission')}
                        </p>
                        <p className={`text-[14px] leading-[16px] ${locale == 'ar' ? "font-['GSSLight']" : "font-[InterRegular]"} text-white`}>
                            {t('transmissionSpecs')?.includes('8') ? <>

                                {t('transmissionSpecs')?.split('8')[0]}
                                <span className='font-["InterRegular"]'>8</span>
                                {t('transmissionSpecs')?.split('8')[1]}
                            </> : t('transmissionSpecs')}


                        </p>

                    </div>
                    <div className='flex flex-col items-center w-[145px]'>
                        <svg xmlns="http://www.w3.org/2000/svg"
                            width="54px"
                            height="54px"
                            viewBox="0 0 24 24"
                            fill="none">
                            <circle cx="12" cy="12" r="5" stroke="#ffffff" strokeWidth="1.5"></circle><path d="M12 7V11" stroke="#ffffff" strokeWidth="1.5" strokeLinecap="round"></path><path d="M13 3.5C13 4.05228 12.5523 4.5 12 4.5C11.4477 4.5 11 4.05228 11 3.5C11 2.94772 11.4477 2.5 12 2.5C12.5523 2.5 13 2.94772 13 3.5Z" fill="#ffffff"></path><path d="M20.5 13C19.9477 13 19.5 12.5523 19.5 12C19.5 11.4477 19.9477 11 20.5 11C21.0523 11 21.5 11.4477 21.5 12C21.5 12.5523 21.0523 13 20.5 13Z" fill="#ffffff"></path><path d="M3.5 13C2.94772 13 2.5 12.5523 2.5 12C2.5 11.4477 2.94772 11 3.5 11C4.05228 11 4.5 11.4477 4.5 12C4.5 12.5523 4.05228 13 3.5 13Z" fill="#ffffff"></path><path d="M6.69685 5.2824C7.08738 5.67292 7.08738 6.30608 6.69685 6.69661C6.30633 7.08713 5.67316 7.08713 5.28264 6.69661C4.89212 6.30608 4.89212 5.67292 5.28264 5.2824C5.67316 4.89187 6.30633 4.89187 6.69685 5.2824Z" fill="#ffffff"></path><path d="M18.7174 17.3034C19.1079 17.6939 19.1079 18.3271 18.7174 18.7176C18.3268 19.1081 17.6937 19.1081 17.3031 18.7176C16.9126 18.3271 16.9126 17.6939 17.3031 17.3034C17.6937 16.9129 18.3268 16.9129 18.7174 17.3034Z" fill="#ffffff"></path><path d="M18.7174 6.69661C18.3268 7.08713 17.6937 7.08713 17.3031 6.69661C16.9126 6.30608 16.9126 5.67292 17.3031 5.2824C17.6937 4.89187 18.3268 4.89187 18.7174 5.2824C19.1079 5.67292 19.1079 6.30608 18.7174 6.69661Z" fill="#ffffff"></path><path d="M6.69685 18.7176C6.30633 19.1081 5.67316 19.1081 5.28264 18.7176C4.89212 18.3271 4.89212 17.6939 5.28264 17.3034C5.67316 16.9129 6.30633 16.9129 6.69685 17.3034C7.08738 17.6939 7.08738 18.3271 6.69685 18.7176Z" fill="#ffffff"></path></svg>
                        <p className={`text-[17px] ${locale == 'ar' ? "font-['GSSMedium']" : "font-[InterBold]"} text-white mt-2.5`}> {t('driveMode')}

                        </p>
                        <p className={`text-[14px] leading-[16px] ${locale == 'ar' ? "font-['GSSLight']" : "font-[InterRegular]"} text-white`}> {t('driveModeSpecs')}
                        </p>

                    </div>
                    <div className='flex flex-col items-center w-[145px]'>
                        <svg xmlns="http://www.w3.org/2000/svg"
                            width="54px"
                            fill='#ffffff'

                            height="54px"
                            viewBox="0 0 94.2 61.1"
                            style={{ enableBackground: 'new 0 0 94.2 61.1' }}
                        >
                            <g transform="translate(0,-952.36218)">
                                <path d="M4.8,954.9c-1,0.1-1.7,1-1.7,2v52c0,1.1,0.9,2,2,2c0.2,0,0.5,0,0.7-0.1c11.3-4.3,25.6-6.9,41.3-6.9s30,2.6,41.3,6.9  c1,0.4,2.2-0.1,2.6-1.1c0.1-0.2,0.1-0.5,0.1-0.7v-52c0-1.1-0.9-2-2-2c-0.2,0-0.5,0-0.7,0.1c-11.3,4.3-25.6,6.9-41.3,6.9  s-30-2.6-41.3-6.9C5.5,954.9,5.2,954.9,4.8,954.9L4.8,954.9z M7.1,959.6c11.4,4,25.1,6.3,40,6.3s28.6-2.4,40-6.3v46.5  c-11.4-4-25.1-6.3-40-6.3s-28.6,2.4-40,6.3V959.6z"></path></g></svg>
                        <p className={`text-[17px] ${locale == 'ar' ? "font-['GSSMedium']" : "font-[InterBold]"} text-white mt-2.5`}>

                            {t('powerDelivery')?.split('29.9')[0]}
                            <span className='font-["InterRegular"]'>29.9</span>
                            {t('powerDelivery')?.split('29.9')[1]}

                        </p>
                        <p className={`text-[14px] leading-[16px] ${locale == 'ar' ? "font-['GSSLight']" : "font-[InterRegular]"} text-white`}> {t('powerDeliverySpecs')}
                        </p>

                    </div>
                    <div className='flex flex-col items-center w-full md:w-[200px]'>
                        <svg xmlns="http://www.w3.org/2000/svg"
                            width="54px"
                            height="54px"
                            viewBox="0 0 24 24"
                            fill="none">
                            <path d="M3 10.4167C3 7.21907 3 5.62028 3.37752 5.08241C3.75503 4.54454 5.25832 4.02996 8.26491 3.00079L8.83772 2.80472C10.405 2.26824 11.1886 2 12 2C12.8114 2 13.595 2.26824 15.1623 2.80472L15.7351 3.00079C18.7417 4.02996 20.245 4.54454 20.6225 5.08241C21 5.62028 21 7.21907 21 10.4167C21 10.8996 21 11.4234 21 11.9914C21 17.6294 16.761 20.3655 14.1014 21.5273C13.38 21.8424 13.0193 22 12 22C10.9807 22 10.62 21.8424 9.89856 21.5273C7.23896 20.3655 3 17.6294 3 11.9914C3 11.4234 3 10.8996 3 10.4167Z" stroke="#ffffff" strokeWidth="1.5"></path><path d="M9.5 12.4L10.9286 14L14.5 10" stroke="#ffffff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path></svg>
                        <p className={`text-[17px] ${locale == 'ar' ? "font-['GSSMedium']" : "font-[InterBold]"} text-white mt-2.5`}> {t('Warranty')}
                        </p>
                        <p className={`text-[14px] leading-[16px] ${locale == 'ar' ? "font-['GSSLight']" : "font-[InterRegular]"} text-white text-center`}> {locale == 'ar' ?

                            <>
                                <span className='font-[InterRegular]'>5</span> {"سنوات"}
                                /
                                <span className='font-[InterRegular]'>{query?.market?.includes('KSA') ? 100 : 150}</span>
                                {` ألف كيلومتر
 
أيهما أقرب`}
                            </>

                            : `5 Years/${query?.market?.includes('KSA') ? '100,000 Km' : '150,000 Km'}
                                    whichever comes first`}</p>

                    </div>
                </div>
            </div>
            <ParallaxSectionTV
                image="https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/72d210ca-a928-46df-936f-76debee31100/public"
                text={t('head_turning_design')}
                buttonText={t('explore_more')}
                isDangeroulyInnerHtml={true}
                height='55vh'
                id='design'
            />
            <div className="relative " style={{ zIndex: 1 }}>
                <ScrollSequence
                    id="sequence1"
                    imagesUrl={exterior}
                    totalFrames={exterior?.length}
                    startTextFrame={6}
                    endTextFrame={exterior?.length - 5}
                    text={t('sequance_head')}
                    description={t('sequance_head_description')}
                />
            </div>
            <FeaturesCards1 />

            <div className="relative" style={{ zIndex: 1 }}>
                <ScrollSequence
                    id="canvas4"
                    imagesUrl={exterior1}
                    totalFrames={exterior1?.length}
                    text={t('led_rear_lamps')}
                    description={t('led_rear_lamps_description')}
                    endTextFrame={100}
                    text2={t('fastback_design')}
                    description2={t('fastback_description')}
                    startTextFrame={30}

                    startTextFrame2={120}
                    endTextFrame2={exterior1?.length}
                />
            </div>


            <VRShowroom />

            <ParallaxSectionTV
                image="https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/5a0f3ad8-cfbb-4d47-8982-a0a347ac9f00/public"
                text={t('tech_enthusiasts')}
                buttonText={t('explore_more')}
                id='technology'
                height='55vh'

            />
            <div className="relative" style={{ zIndex: 1 }}>
                <ScrollSequence
                    id="sequence4"
                    imagesUrl={ScreenImages}
                    totalFrames={ScreenImages?.length}
                    text={t('panoramic_display')}
                    text2={t('steering_wheel')}
                    description2={t('steering_wheel_description')}
                    description={t('panoramic_display_description')}
                    endTextFrame={111}
                    startTextFrame={12}
                    startTextFrame2={130}
                    endTextFrame2={ScreenImages?.length}
                />
            </div>
            <FeaturesCards3 small={true} />




            <ParallaxSectionTV
                height='55vh'
                image="https://imagedelivery.net/2Dh6erMZ0IA4Y2r-mRikDg/e2087897-6e15-4f58-2257-400653ad9300/public"
                text={t('comfort')}
                buttonText={t('explore_more')}
                id='comfort'
            />

            <FeaturesCards2 pb={true} />
            <EngineSection />
            <SpecsCards model="K2" id={'safety'} />
            <SpecsSection />
        </main>
    );
}

export async function getStaticProps ({ locale }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ['common'])),
        },
    };
}
